[workspace]
members=[ "ai-depin-settlement","delegated-proof-of-stake", "futarchy-dao", "liquid-restaking", "liquid-staking", "merkle-whitelist-token-sale", "nft-marketplace","spl-staking"]
resolver="2"
